### ISSUE TITLE
Tracking issue for adding custom plugins

### ISSUE THREAD

**Issue by andyxning** [kubernetes/node-problem-detector#150]
This is a tracking issue for what we still need to do after adding custom plugins in #145 .

- [x] Complete `pkg/custompluginmonitor/README.md`
- [x] Support per-rule interval
- [x] Emitting events when Condition changes.  
* Added in https://github.com/kubernetes/node-problem-detector/pull/151
- [x] support unknown condition status. 
* Added in https://github.com/kubernetes/node-problem-detector/pull/151

**Comment by Random-Liu** [comment]
> Emitting events when Condition changes

Comparing with actual event, condition change should be rare. If node condition changes too frequently, it will cause even more issues, e.g. kubelet can't update node condition.

So I think it's fine to generate an event for condition change.

**Comment by Random-Liu** [comment]
We also need to add integration test for custom plugin in https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/node_problem_detector_linux.go

**Comment by byxorna** [comment]
Is this still in flight? `master` never registers the custom plugin with `registerLogWatcher(customPluginName, ...)`. Is this something that is actively being worked on?

**Comment by andyxning** [comment]
@byxorna For now, i am ok to work on any problem you have. But as @Random-Liu has no time to focus on this project for now, i can only help to address any issues or review PRs.

For merging or any other problem, we can only wait @Random-Liu to come back. :)

**Comment by byxorna** [comment]
@andyxning cool, thank you! Is the custom plugin in a state where you will accept a PR to enable it?

Its unclear to me whether it is feature complete (but not hooked up) or still a WIP, because master has https://github.com/kubernetes/node-problem-detector/blob/master/config/custom-plugin-monitor.json committed, but will refuse to load that config due to `No create function found for plugin "custom"`

**Comment by andyxning** [comment]
@byxorna 

For now it is usable in the master branch. But there do have an enhance PR from @Random-Liu to enhance custom plugin manager in https://github.com/kubernetes/node-problem-detector/pull/151.

Actually, i have used custom plugin manager internally with #151 . I will dig into the reason about `No create function found for plugin "custom"`.

**Comment by andyxning** [comment]
@byxorna What command line did you use in your usage?

**Comment by andyxning** [comment]
@byxorna Seems like that you run custom plugin monitor with `--system-log-monitors`. Just like something: `--system-log-monitors=custom-plugin-monitor.json`.

In the [README about flags](https://github.com/kubernetes/node-problem-detector#flags), it is documented that custom plugin monitor configuration file should only be used with `--custom-plugin-monitors` command line instead of `--system-log-monitors`.

**Comment by byxorna** [comment]
@andyxning ah, thank you! that behavior is non-intuitive; I was passing the custom.json to `--system-log-monitors`.

An aside, but what is the intent of keeping `--system-log-monitors` and `--custom-plugin-monitors` separate? I imagine its operationally easier to just keep a dir with all your monitors (custom or otherwise) and let the config loading/parsing in NPD sort them out :)

**Comment by andyxning** [comment]
@byxorna That's a good UX enhance suggestion. The reason to do seperate `--system-log-monitors` and `--custom-plugin-monitors` is they do have some different configuration. We can merge system log monitors config and custom plugin monitors together, but that will make the code more complicated and hard to maintain. By splitting them, we can make the code more moduling. :)

**Comment by byxorna** [comment]
@andyxning on the other hand, it feels messy to make end users feel pain caused by the internal design details of this software; they shouldnt have to know or care _how_ its implemented. 😄

**Comment by andyxning** [comment]
Close this tracking issue as all tracking problems has been addressed.

> We also need to add integration test for custom plugin in https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/node_problem_detector_linux.go

@Random-Liu I have recored this in my calendar and will complete this later. Since this is a tracking issue for adding custom plugin support in node-problem-detector, it is not suitable for keeping record this problem in this issue. :)
