### ISSUE TITLE
Implement NPD metrics mode

### ISSUE THREAD

**Issue by xueweiz** [kubernetes/node-problem-detector#284]
Here is the [proposal](https://docs.google.com/document/d/1SeaUz6kBavI283Dq8GBpoEUDrHA2a795xtw0OvjM568/edit#heading=h.xw2rl6ej7zhr).

This issue tracks the implementation of the proposal:
- [x] Check-in the proposal to NPD project's [README](https://github.com/kubernetes/node-problem-detector/tree/v0.6.3#links)   (#285)
- [x] Refactor problem daemon registration and initialization, so that they are more modular, and rely on less [per-daemon initialization code duplication](https://github.com/kubernetes/node-problem-detector/blob/4880be842d32dfcf31d2a8f01070d17473732a88/cmd/node_problem_detector.go#L73).  (#275)
- [x] Refactor events/condition reporting into k8s_exporter. (#275)
- [x] Add a SystemStatsMonitor problem daemon, to monitor some system metrics; and add an optional Prometheus metrics exporter. (#286 #275)
- [x] Implement feature in System Log Monitor and Custom Plugin Monitor, to allow them to report metrics. (#300 #315 )
- [x] Implement option for disabling problem daemons at compile time. (#294 )
- [x] ~~Implement option for disabling exporters at compile time.~~ (Current exporters includes a k8s exporter and Prometheus exporter. Since they are commonly used, compile time disabling is not high priority for now. We can re-prioritize if the situation changes.)

**Comment by xueweiz** [comment]
Now that #315 is merged, this issue is finally complete! It will be release in NPD v0.7.0

Huge thanks to Zhen, Lantao and Andy for the reviews and feedback!

There are a few follow up improvements, most importantly, e2e tests for NPD (#296). I really want e2e test to happen, so that we can have more confidence when changing NPD code.
