### ISSUE TITLE
NPD Kubernetes 1.6 Planning

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/node-problem-detector#58]
NPD (node problem detector) is introduced in Kubernetes 1.3 as a default add-on in GCE cluster.

At that time, it is mainly targeted on default GCE Kubernetes setup. However, as time goes by, some limitations were found such as [Journald support](#14), [Authentication Issue](#21), [Scalability Issue](#37)  which affected the adoption of NPD in many other environment.

In Kubernetes 1.6, we plan to invest some time to improve NPD, make it production ready and rollout it in GKE.

Here are the working items and priorities:
- [x] **[P0] Journald support.** Many important OS distros are using systemd now, such as GCI, CoreOS, CentOS etc. This is essential for NPD adoption. (Issue:  https://github.com/kubernetes/node-problem-detector/issues/14, PR: https://github.com/kubernetes/node-problem-detector/pull/39, https://github.com/kubernetes/node-problem-detector/pull/33, @AdoHe) 
- [x] **[P0] Apiserver client option override.** By default, NPD is running as DaemonSet and [use `InClusterConfig` to access apiserver](http://kubernetes.io/docs/user-guide/accessing-the-cluster/#accessing-the-api-from-a-pod). However, this does not work when service account is not available. (Issue: https://github.com/kubernetes/node-problem-detector/issues/27, https://github.com/kubernetes/node-problem-detector/issues/21). We should make the apiserver client option configurable, so that user can customize it based on their cluster setup. **This is prerequisite of Standalone mode** (PR: https://github.com/kubernetes/node-problem-detector/pull/49, @andyxning)
- [x] **[P0] Standalone mode.** Make it possible to run NPD standalone, possibly as a systemd service. DaemonSet is easy to deploy and manage. However, docker still stops all containers when it's dead ([`live-restore`](https://docs.docker.com/engine/admin/live-restore/) is still [in validation](https://github.com/kubernetes/kubernetes/issues/38303)). Because of this, NPD may not be able to detect problems when docker is unresponsive. (Issue: #76)
- [ ] **[P1] Integrate NPD with K8s e2e framework.** NPD is already running in e2e cluster, but the information it collects is not well-surfaced from the test framework. We should make it visible by failing the test or collecting via a dashboard (Issue: https://github.com/kubernetes/kubernetes/issues/30811).
- [x] **[P1] Scalability and performance.** https://github.com/kubernetes/node-problem-detector/issues/85
  - [x] Some known performance issue needs to be fixed in NPD, such as reduce apiserver access (https://github.com/kubernetes/node-problem-detector/issues/37), and improve log parsing efficiency. (https://github.com/kubernetes/node-problem-detector/pull/79, #84)
  - [x] More benchmark to verify the performance of NPD. Both benchmark for NPD resource usage and apiserver load introduced by NPD (https://github.com/kubernetes/node-problem-detector/issues/50, @shyamjvs, https://github.com/kubernetes/node-problem-detector/issues/85).
- [ ] **[P2] Formalize the Project.** Formalize the process of the project, including:
  - [x] https://github.com/kubernetes/node-problem-detector/pull/66 Add change log. (#45) [P2]
  * Define release process. (#67) [P2]
  * Add pre/post submit e2e test. (#43) [P3]
- [x] **[P2] Docker problem detection.** Although kernel monitor could be extended to monitor other logs, it still needs some code change to achieve that. We should cleanup the code to make it easier to monitor other logs and add clear documentation for it. (https://github.com/kubernetes/node-problem-detector/issues/44) (#88) (PR: https://github.com/kubernetes/node-problem-detector/pull/88, https://github.com/kubernetes/node-problem-detector/pull/92, https://github.com/kubernetes/node-problem-detector/pull/94)
- [ ] **[P3] 3rd party problem daemon integration.** Kernel monitor is designed to detect known kernel problems with minimum overhead, it is not expected to be a comprehensive solution. NPD should be extensible to integrate with more small problem daemons or more mature solution. (https://github.com/kubernetes/node-problem-detector/issues/35)

Note that only P0s are release blocker.

@dchen1107 @fabioy @ajitak 
/cc @kubernetes/sig-node-misc

**Comment by Random-Liu** [comment]
Close this issue since all P0 items are done.
